apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-app
  labels:
    app: ruby-app
    env: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ruby-app
  template:
    metadata:
      labels:
        app: ruby-app
        env: staging
    spec:
      containers:
      - name: ruby-app
        image: 10.10.3.1:5000/ruby-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ruby-app
  labels:
    env: staging
spec:
  type: LoadBalancer
  selector:
    app: ruby-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
